#!/bin/bash


mpicc -lGL -lGLU -lglut -lpng -lgmp -lm mandelbrot.c -o mandelexec -Ofast
compiled=$?
if [[ $compiled == 0 ]]
	then mpirun -np 4 -hostfile hosts.txt ~/cs/parallel/mandel/mandelexec $@
fi
# mpirun -np 16 -hostfile hosts.txt mandelexec $@
