#!/bin/bash

# width iterations resolution

# mpirun -np 48 -hostfile hosts.txt ./a.out 1000 1000 1000000
# mpirun -np 48 -hostfile hosts.txt ./a.out 100 100 100000
# mpirun --host localhost -np 4 ./a.out 1000 10 1000000 2> /dev/null & # Maximum double precision
# mpirun --host localhost -np 4 ./a.out 1000 10 100000

# Serial - 2
echo ------ SERIAL ------
mpirun -np 2 --host localhost ./a.out 100 160 100000

# One node - 4
echo ------ THREE CORES ------
mpirun -np 3 --host localhost ./a.out 100 160 100000
echo ------ FOUR CORES ------
mpirun -np 4 --host localhost ./a.out 100 160 100000

# Two nodes - 6
echo ------ FIVE CORES ------
time mpirun -np 5 --host localhost,kirby ./a.out 100 160 100000
echo ------ SIX CORES ------
time mpirun -np 6 --host localhost,kirby ./a.out 100 160 100000

# Two nodes - 8
echo ------ SEVEN CORES ------
time mpirun -np 7 --host localhost,kirby ./a.out 100 160 100000
echo ------ EIGHT CORES ------
time mpirun -np 8 --host localhost,kirby ./a.out 100 160 100000

# Three nodes - 12
# echo ------ TWELVE CORES ------
# mpirun -np 12 --host localhost,kirby,wall ./a.out 100 160 100000

# Two nodes - 16
# mpirun -np 16 --host c,fortran ./a.out 100 100 100000

# Four nodes - 32
# mpirun -np 32 --host c,fortran,lisp,ruby ./a.out 100 100 100000

# mpirun -np 4 --host james@jhoughton.me ./a.out 100 100 100000
